export const environment = {
  production: false,
  uVersion: "u1",
  mVersion: "m1",
  mvVersion: "v6",
  mockBackend: false,
  platformName: "Dev Natal777bet",
  platformGroup: "O JS Group",
  baseUrl: "",
  appPackageName: "com.ttgroup.phxj",
  captcha: "/japi/user/captcha/image",
  appVersion: "1.0.0",
  s3URLImages: "https://resources.ttgroup.vip/icon",
  snowEffects: "snowflake",
};
