export const environment = {
  production: true,
  uVersion: "u1",
  mVersion: "m1",
  mvVersion: "v7",
  mockBackend: false,
  platformName: "Carnaval777Bet",
  platformGroup: "O TT Group",
  baseUrl: "",
  appPackageName: "com.ttgroup.phxj",
  captcha: "/japi/user/captcha/image",
  appVersion: "1.0.0",
  s3URLImages: "https://resources.ttgroup.vip/icon",
  snowEffects: "snowDot",
};
