export enum FeeRateKeyEnum {
  "DAILY_FEE" = "DAILY_FEE",
  "GST" = "GST",
  "LOAN_AMOUNT" = "LOAN_AMOUNT",
  "LOAN_INTEREST" = "LOAN_INTEREST",
  "PENALTY_INTEREST" = "PENALTY_INTEREST",
  "PROCESSING_FEE" = "PROCESSING_FEE",
  "REDUCTION_AMOUNT" = "REDUCTION_AMOUNT",
  "SERVICE_FEE" = "SERVICE_FEE",
}
